const appname = "Society Management";
const appversion = "Version 1.0.0";
const credits = "@Zap Solutionz";
const email = "Email";
const emailHint = 'admin@gmail.com';
const password = "Password";
const passwordHint = "*******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Zap solutionz";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign Up";
const createNewAccount = "or Create a new account";
const loginWith = "Log in with";
const privacypolicy = "Privacy Policy";
const termAndCond = "Terms And Conditions";
const alreadyHaveAccount = "Already have an account? ";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchanything = "Search any thing...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "T Shirts",
    girlsDress = "Girls Dresses",
    featuredProduct = "Featured Products",
    featuredCategories = "Featured Categories";

const womenClothing = "Women Clothing",
    menClothingFashion = "Men Clothing & Fashion",
    compAccess = "Computer & Accessories",
    automobile = "Automobile",
    kidtoys = "Kids & Toys",
    sports = "Sports",
    cellphone = "Cellphone & Tabs",
    furniture = "Furniture",
    jewelery = "Jewellery";
